# Generated by Django 5.0.6 on 2024-06-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_authorsbooks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(through="book.AuthorsBooks", to="book.author"),
        ),
    ]
