# Generated by Django 5.0.6 on 2024-06-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_remove_book_authors_book_authors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authorsbooks",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book.author"
            ),
        ),
        migrations.AlterField(
            model_name="authorsbooks",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book.book"
            ),
        ),
    ]
