# Generated by Django 5.0.6 on 2024-07-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_authorsbooks_author_alter_authorsbooks_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.CheckConstraint(
                check=models.Q(("name__iexact", models.F("name")), _negated=True),
                name="book_tag_name_check",
            ),
        ),
    ]
