# Generated by Django 5.0.6 on 2024-07-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_tag_tag_book_tag_name_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(to="book.tag"),
        ),
    ]
