# Generated by Django 5.0.6 on 2024-07-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_book_tags"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag",
            name="book_tag_name_check",
        ),
    ]
