# Generated by Django 5.0.6 on 2024-07-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_remove_tag_book_tag_name_check"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorsbooks",
            options={"verbose_name": "Authors and Books"},
        ),
    ]
