# Generated by Django 5.0.6 on 2024-07-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_alter_authorsbooks_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authorsbooks",
            options={"verbose_name": "Author and Book"},
        ),
    ]
