# Generated by Django 5.0.6 on 2024-07-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0012_alter_authorsbooks_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("title",)},
        ),
    ]
