# Generated by Django 5.0.6 on 2024-07-02 11:20

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0003_remove_nic_reader_nic_date_check_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nic",
            name="expiration_date",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("delivery_date"),
                    "+",
                    models.Value(datetime.timedelta(days=1826, seconds=21600)),
                ),
                output_field=models.DateField(),
            ),
        ),
    ]
