# Generated by Django 5.0.6 on 2024-07-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0005_reader_nic"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="nic",
            table_comment="National Identity Card",
        ),
    ]
