# Generated by Django 5.0.6 on 2024-07-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0006_alter_nic_table_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reader",
            name="nic",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reader.nic",
            ),
        ),
    ]
