# Generated by Django 5.0.6 on 2024-07-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0007_alter_reader_nic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reader",
            options={"default_related_name": "%(app_label)s_%(model_name)s"},
        ),
    ]
