# Generated by Django 5.0.6 on 2024-07-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0008_alter_reader_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nic",
            options={"get_latest_by": ["delivery_date", "-expiration_date"]},
        ),
    ]
